create table if not exists public.user_account (
  user_account_id bigint generated by default as identity primary key,
  user_name text not null unique,
  full_name text,
  sponsor text,
  placement text,
  "group" text,
  account_type text,
  zero_one text,
  code_payment text check (code_payment is null or code_payment in ('PD', 'FS')),
  city text,
  province text,
  region text,
  country text,
  date_created timestamptz not null default now(),
  date_updated timestamptz not null default now()
);

create index if not exists idx_user_account_user_name
  on public.user_account (user_name);

create index if not exists idx_user_account_full_name
  on public.user_account (full_name);

create index if not exists idx_user_account_zero_one
  on public.user_account (zero_one);

create index if not exists idx_user_account_date_updated
  on public.user_account (date_updated desc);

create or replace function public.set_user_account_date_updated()
returns trigger
language plpgsql
as $$
begin
  new.date_updated = now();
  return new;
end;
$$;

drop trigger if exists trg_user_account_date_updated on public.user_account;

create trigger trg_user_account_date_updated
before update on public.user_account
for each row
execute function public.set_user_account_date_updated();

alter table public.user_account enable row level security;

drop policy if exists "Authenticated users can read user_account" on public.user_account;
create policy "Authenticated users can read user_account"
on public.user_account
for select
to authenticated
using (true);

drop policy if exists "Authenticated users can insert user_account" on public.user_account;
create policy "Authenticated users can insert user_account"
on public.user_account
for insert
to authenticated
with check (true);

drop policy if exists "Authenticated users can update user_account" on public.user_account;
create policy "Authenticated users can update user_account"
on public.user_account
for update
to authenticated
using (true)
with check (true);

insert into public.user_account (
  user_name,
  full_name,
  date_created,
  date_updated
)
select
  trim(u.username),
  nullif(trim(u.member_name), ''),
  coalesce(u.created_at, now()),
  coalesce(u.created_at, now())
from public.users_directory as u
where nullif(trim(u.username), '') is not null
on conflict (user_name) do nothing;
