export type SaleEntry = {
  id: string;
  savedAt: string;
  event: string;
  date: string;
  pgfNumber: string;
  memberName: string;
  username: string;
  newMember: string;
  memberType: "distributor" | "platinum" | "gold" | "silver" | "";
  packageType: string;
  toBlister: string;
  originalPrice: string;
  quantity: string;
  blisterCount: string;
  discount: string;
  priceAfterDiscount: string;
  oneTimeDiscount: string;
  totalSales: string;
  modeOfPayment: "cash" | "bank" | "ewallet" | "cheque" | "";
  paymentModeType: "maya" | "gcash" | "bdo" | "bpi" | "na" | "";
  referenceNumber: string;
  modeOfPayment2: "cash" | "bank" | "ewallet" | "cheque" | "";
  paymentModeType2: "maya" | "gcash" | "bdo" | "bpi" | "na" | "";
  referenceNumber2: string;
  amount2: string;
  releasedBottles: string;
  releasedBlister: string;
  toFollowBottles: string;
  toFollowBlister: string;
  remarks: string;
  receivedBy: string;
  collectedBy: string;
};
